image: rootproject/root-ubuntu16

# Build the project with cmake, including download of BAT.
build:cmake:minimal:
  stage: build
  script:
    - cmake --version
    - echo `root-config --version`
    - mkdir -p build
    - cd build
    - cmake -DBUILTIN_BAT=TRUE -DKLFITTER_INSTALL_TESTS=TRUE ..
    - make -j || make -j || make -j
  artifacts:
    paths:
    - build
    expire_in: 2 days

# Build the project with the traditional Makefile.
build:make:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - ./../cmake/CompileBAT.sh
    - cd ..
    - (make -j || make -j || make -j)
    - (make -j tests || make -j tests)
  artifacts:
    paths:
      - build
      expire_in: 2 days

# Run unit tests based on the cmake minimal setup.
test:cmake:minimal:
  stage: test
  before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`root-config --libdir`
  script:
    - ./build/test-bin/test-ljets-lh ./
  dependencies:
    - build:cmake:minimal

# Run unit tests based on the Makefile setup.
test:make:
  stage: test
  before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`root-config --libdir`
  script:
    - ./build/test-ljets-lh ./
  dependencies:
    - build:make
