# Copyright (c) 2009--2018, the KLFitter developer team
#
# This file is part of KLFitter.
#
# KLFitter is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# KLFitter is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with KLFitter. If not, see <http://www.gnu.org/licenses/>.

image: rootproject/root-ubuntu16

stages:
  - build-dependencies
  - build
  - test

variables:
  SOURCE_DIR: '$CI_PROJECT_DIR'
  BUILD_DIR: '$CI_PROJECT_DIR/build'
  BATINSTALLDIR: '$CI_PROJECT_DIR/external/BAT'
  CMAKE_OPTION: '-DKLFITTER_INSTALL_TESTS=TRUE'


# Configuration for saving build artifacts.
.build_artifacts: &build_artifacts
  expire_in: 2 days
  paths:
  - build

.build_artifacts_ext_bat: &build_artifacts_ext_bat
  <<: *build_artifacts
  paths:
    - build
    - $BATINSTALLDIR

# Configuration for CI conditions.
.exec_manual_and_failable: &exec_manual_and_failable
  when: manual
  allow_failure: true

# The basic cmake configuration for making KLFitter.
.cmake_klfitter: &cmake_klfitter
  stage: build
  script:
    - mkdir -p $BUILD_DIR && cd $BUILD_DIR
    - cmake $CMAKE_OPTION $SOURCE_DIR
    - make -j || make -j || make -j


# Build the project with cmake. This includes an automatic download of the BAT
# library, and KLFitter and BAT are compiled and linked against each other. This
# is the recommended way to build KLFitter.
cmake-build:
  <<: *cmake_klfitter
  artifacts: *build_artifacts
  variables:
    CMAKE_OPTION: '-DBUILTIN_BAT=TRUE -DKLFITTER_INSTALL_TESTS=TRUE'


# Alternative build 1: build the project with cmake, but use an existing version
# of the BAT library. For that, we use the script ./cmake/CompileBAT.sh to
# download and install BAT (without cmake). Then cmake uses the
# ./cmake/FindBAT.cmake file to locate that external library.
build-BAT:
  <<: *exec_manual_and_failable
  stage: build-dependencies
  artifacts: *build_artifacts_ext_bat
  script:
    - sudo apt-get update
    - sudo apt-get install wget
    - ./cmake/CompileBAT.sh $BATINSTALLDIR


cmake-build-with-prebuilt-BAT:
  <<: *exec_manual_and_failable
  <<: *cmake_klfitter
  stage: build
  variables:
    SOURCE_DIR: '$CI_PROJECT_DIR/KLFitter'
  artifacts: *build_artifacts_ext_bat
  before_script:
    - mkdir -p $SOURCE_DIR
    - mv CMakeLists.txt cmake include src tests $SOURCE_DIR
  after_script:
    - mv $SOURCE_DIR/* ./
    - rm -rf $SOURCE_DIR
  dependencies:
    - build-BAT


# Alternative build 2: build the project with the traditional Makefile. Again
# this utilises the script ./cmake/CompileBAT.sh to download and install BAT (no
# use of Makefile). Then the Makefile locates the BAT installation with the
# $BATINSTALLDIR variable.
makefile-build:
  <<: *exec_manual_and_failable
  stage: build
  artifacts: *build_artifacts_ext_bat
  script:
    - make -j || make -j || make -j
    - make -j tests || make -j tests
    - make install || make install
  dependencies:
    - build-BAT


# Run unit tests based on the cmake setup.
cmake-test:
  stage: test
  before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BUILD_DIR/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`root-config --libdir`
  script:
    - ./build/test-bin/test-ljets-lh ./
  dependencies:
    - cmake-build
