image: rootproject/root-ubuntu16

stages:
  - pre-build
  - build
  - test

# Download and build BAT.
pre-build:BAT:
  stage: pre-build
  before_script:
    - sudo apt-get update
    - sudo apt-get install wget
  script:
    - mkdir -p build
    - cd build
    - ./../cmake/CompileBAT.sh
  artifacts:
    paths:
    - build
    expire_in: 2 days

# Build the project with cmake, including download of BAT.
build:cmake:minimal:
  stage: build
  script:
    - cmake --version
    - echo `root-config --version`
    - mkdir -p build
    - cd build
    - cmake -DBUILTIN_BAT=TRUE -DKLFITTER_INSTALL_TESTS=TRUE ..
    - make -j || make -j || make -j
  artifacts:
    paths:
    - build
    expire_in: 2 days

# Build the project with the traditional Makefile.
build:make:
  stage: build
  script:
    - export BATINSTALLDIR=$PWD/build
    - make -j || make -j || make -j
    - make -j tests || make -j tests
    - make install || make install
  dependencies:
    - build:BAT
  artifacts:
    paths:
    - build
    expire_in: 2 days

# Run unit tests based on the cmake minimal setup.
test:cmake:minimal:
  stage: test
  before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`root-config --libdir`
  script:
    - ./build/test-bin/test-ljets-lh ./
  dependencies:
    - build:cmake:minimal

# Run unit tests based on the Makefile setup.
test:make:
  stage: test
  before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`root-config --libdir`
  script:
    - ./build/test-ljets-lh ./
  dependencies:
    - build:make
