image: rootproject/root-ubuntu16

stages:
  - pre-build
  - build
  - test


# Download and build BAT.
pre-build:BAT:
  stage: pre-build
  before_script:
    - sudo apt-get update
    - sudo apt-get install wget
  script:
    - ./cmake/CompileBAT.sh
  artifacts:
    paths:
    - external/BAT
    expire_in: 2 days


# Build the project with cmake, including download of BAT.
build:cmake:minimal:
  stage: build
  before_script:
    - mkdir -p build
  script:
    - cd build
    - cmake -DBUILTIN_BAT=TRUE -DKLFITTER_INSTALL_TESTS=TRUE ..
    - make -j || make -j || make -j
  artifacts:
    paths:
    - build
    expire_in: 2 days


# Build the project with cmake, using local version of BAT.
build:cmake:
  stage: build
  before_script:
    - export BATINSTALLDIR=$PWD/external/BAT
    - mkdir -p build KLFitter
    - mv CMakeLists.txt cmake include src tests KLFitter/
  script:
    - cd build
    - cmake -DKLFITTER_INSTALL_TESTS=TRUE ../KLFitter
    - make -j || make -j || make -j
  dependencies:
    - pre-build:BAT
  artifacts:
    paths:
    - build
    expire_in: 2 days


# Build the project with the traditional Makefile.
build:make:
  stage: build
  allow_failure: true
  before_script:
    - export BATINSTALLDIR=$PWD/external/BAT
  script:
    - make -j || make -j || make -j
    - make -j tests || make -j tests
    - make install || make install
  dependencies:
    - pre-build:BAT
  artifacts:
    paths:
    - build
    expire_in: 2 days


# Run unit tests based on the cmake minimal setup.
test:cmake:minimal:
  stage: test
  before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`root-config --libdir`
  script:
    - ./build/test-bin/test-ljets-lh ./
  dependencies:
    - build:cmake:minimal


# Run unit tests based on the cmake setup with local BAT.
test:cmake:
  stage: test
  before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/external/BAT/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`root-config --libdir`
  script:
    - ./build/test-bin/test-ljets-lh ./
  dependencies:
    - pre-build:BAT
    - build:cmake


# Run unit tests based on the Makefile setup.
test:make:
  stage: test
  allow_failure: true
  before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/external/BAT/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`root-config --libdir`
  script:
    - ./build/test-ljets-lh ./
  dependencies:
    - pre-build:BAT
    - build:make
